version: 2

project_name: crate-operator

builds:
  - id: crate-operator
    binary: crate-operator
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.buildVersion={{ .Tag }}

archives:
  - id: binaries
    ids:
      - crate-operator
    formats:
      - binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  disable: true

blobs:
  - provider: s3
    endpoint: "{{ .Env.R2_ENDPOINT }}"
    region: auto
    bucket: crate-operator
    directory: "staging/version/{{ .Tag }}"
